templates:
  tv:
    series:
      settings:
        shows:
          set:
            path: ~/Media/TV Shows/{{series_name}}/Season {{series_season}}
      shows:
        - Mr.Robot:
            quality: 720p|1080p
            begin: S04E01
        - Power:
            quality: 720p|1080p
            begin: S03E01
            season_packs: yes
        - Tom Clancy's Jack Ryan:
            quality: 1080p
            begin: S02E01
        - Silicon Valley:
            quality: 1080p
            begin: S06E01
        - Ballers:
            quality: 1080p
            begin: S03E01
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: user
      password: password 

tasks:
  Mr.Robot:
    priority: 1
    rss: "https://showrss.info/show/273.rss"
    template: tv
  Power:
    priority: 2
    rss: "https://showrss.info/show/343.rss"
    template: tv
  Tom Clancy's Jack Ryan:
    priority: 3
    rss: "https://showrss.info/show/1037.rss"
    template: tv
  Silicon Valley:
    priority: 4
    rss: "https://showrss.info/show/275.rss"
    template: tv
  Ballers:
    priority: 5
    rss: "https://showrss.info/show/310.rss"
    template: tv

schedules:
  - tasks: '*'
    interval:
      minutes: 10
